# Generated by Django 3.2.9 on 2021-11-20 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
                ('index', models.IntegerField(default=0, verbose_name='Higher index will be priority')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Time')),
                ('last_modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sidebar Name')),
                ('content', models.TextField(verbose_name='Content')),
                ('order', models.IntegerField(unique=True, verbose_name='Order')),
                ('is_enable', models.BooleanField(default=False, verbose_name='Enable')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Time')),
                ('last_modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Time')),
                ('last_modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
                ('publish_status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1, verbose_name='Post Publish Status')),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Time')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Time')),
                ('last_modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='All Tags')),
            ],
        ),
    ]
