# Generated by Django 3.2.9 on 2021-11-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211120_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='notion_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
