# Generated by Django 3.2.9 on 2021-11-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_notion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='notion_type',
            field=models.CharField(choices=[('p', 'Page Type'), ('d', 'Database Type'), ('b', 'Block Type')], default='d', max_length=1, verbose_name='Notion ID Type'),
        ),
    ]
