# Generated by Django 3.2.9 on 2021-12-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_notion_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('index',)},
        ),
    ]
