# Generated by Django 3.2.9 on 2021-12-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SideBar',
        ),
    ]
